# Read the Docs configuration file
version: 2

# Set the OS, Python version, and other tools
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      # Commands to run before the main build
      - pip install pdoc3
      - pip install -e .
      - chmod +x docs/build_docs.sh
      - cd docs && ./build_docs.sh

# Sphinx configuration (required by Read the Docs)
sphinx:
  configuration: docs/conf.py

# Python requirements
python:
  install:
    - method: pip
      path: .