name: ProtPetigram CI/CD

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest matplotlib pandas numpy biopython rich rich-argparse
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -e .
    
    - name: Create test data directory
      run: |
        mkdir -p data/test
        # Create mock data for testing
        echo "Sample test data" > data/test/sample.csv
    
    - name: Copy test data from repository
      run: |
        if [ -d "test/data" ]; then
          cp -r test/data/* data/test/
        else
          # Alternative: Use data from the main data directory if available
          if [ -d "data" ] && [ -f "data/JCI146771_Mouse_peptides_peaks_online.csv" ]; then
            cp data/JCI146771_Mouse_peptides_peaks_online.csv data/test/
            cp data/uniprotkb_proteome_UP000000589_AND_revi_2025_03_12.fasta data/test/ || echo "FASTA file not found, tests may fail"
          fi
        fi
    
    - name: Run tests
      run: |
        pytest -xvs

  build-n-publish:
    name: Build and publish Python distributions to PyPI
    needs: test
    runs-on: ubuntu-latest
    # Only run this job if we're pushing a tag that starts with 'v'
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: python -m build
    
    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
        skip_existing: true
    
    - name: Publish package to PyPI
      if: startsWith(github.ref, 'refs/tags/v')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}